name: Frontend pipeline

on:
  # Run for every push event
  push:
  # Run for pull requests (excluding drafts)
  pull_request:
    types: [ opened, reopened, closed ]

jobs:
  # Install dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Node.js 
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

  # Run ESLint
  eslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set working directory
        run: cd ~
      - name: List
        run: ls
      - name: Run ESLint
        run: npm run lint 

  # Build the project
  build:
    runs-on: ubuntu-latest
    needs: [ setup, eslint ]
    steps:
      - name: Build the project
        run: npm run build

  # Run unit tests
  test:
    runs-on: ubuntu-latest
    needs: [ setup, build ]
    steps:
      - name: Run tests
        run: npm test
        
  # Job to run SonarQube analysis
  sonarcloud:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone improves report relevancy
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: kvikktrip
          SONAR_PROJECT_KEY: kvikktrip_kvikktrip-frontend

