name: Frontend pipeline

on:
  # Run for every push event
  push:
  # Run for pull requests (excluding drafts)
  pull_request:
    types: [ opened, reopened, closed ]

jobs:
  # Install dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Node.js 
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

  # Run ESLint
  eslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      # Install ESLint and configuration
      - name: Install ESLint
        run: npm install --save-dev eslint eslint-config-react-app

      - name: Run ESLint
        run: npm run lint 

  # Build the project
  build:
    runs-on: ubuntu-latest
    needs: [ setup, eslint ]
    steps:
      - uses: actions/checkout@v3

      - name: Build the project
        run: npm run build

  # Run unit tests
  test:
    runs-on: ubuntu-latest
    needs: [ setup, build ]
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: npm test
        
  # Job to run SonarQube analysis
  sonarcloud:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone improves report relevancy
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            sonar.organization=kvikktrip
            sonar.projectKey=kvikktrip_kvikktrip-frontend

