name: Static Analysis

on:
  # Run for pull requests (excluding drafts)
  pull_request:
    types: [ opened, reopened]
    # Run on branches develop and main
    branches: 
      - main
      - develop
  push:
    branches:
      - main

jobs:        
  # Job to run SonarQube analysis
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone improves report relevancy
          fetch-depth: 0
          
      # Download coverage report artifact
      - name: Download coverage report
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: coverage-report
          workflow: test.ym
          path: coverage/lcov.info
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=kvikktrip
            -Dsonar.projectKey=kvikktrip_kvikktrip-frontend
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src/
